export * from './ISubmitUseCase'
export * from './IFetchSubmissionUseCase'
export * from './IFetchSolvedUseCase'
export * from './IPracticalSubmitUseCase'
export * from './IFetchPracticalUseCase'
export * from './IFetchSolvedPracticalUseCase'
export * from './IFetchAllSubmissionUseCase'
