name: Build and publish submission service to Docker Hub

on:
  push:
    branches: ['main']
    paths:
      - "submission-service/**"
  workflow_dispatch:
  
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: List contents of the repo
        run: |
          pwd
          ls -R
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./submission-service/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: fazalahamed628774/submission-service:latest
          no-cache: true
          build-args: |
            BUILDKIT_INLINE_CACHE=0
          outputs: type=docker,dest=/tmp/docker-image.tar
        env:
          DOCKER_BUILDKIT: 1
          BUILDX_NO_DEFAULT_LOAD: true

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: /tmp/docker-image.tar

      - name: Display structure of built files
        if: always()
        run: ls -R ./submission-service/